### PR TITLE
Don't reset collectors when Cartridge roles hot reload

### LINKED ISSUE #334: Cartridge role reload resets metrics data
`metrics` package should support role reload, while it resets all observations and collectors.

### Steps to reproduce
1. Create template application
   ```bash
   cartridge create --name test-app
   ```

2. Change `init.lua`
   ```lua
   local ok, err = cartridge.cfg({
       roles_reload_allowed = true,
       roles = {
           'cartridge.roles.vshard-storage',
           'cartridge.roles.vshard-router',
           'cartridge.roles.metrics',
           'app.roles.custom',
       },
   })
   ```

3. Start an application
   ```bash
   cartridge build
   cartridge start -d
   cartridge replicasets setup --bootstrap-vshard
   ```

4. Connect to instance
   ```bash
   cartridge enter router
   ```

5. Execute reload
     ```
    test-reload.router> metrics = require('metrics')
    ---
    ...
    
    test-reload.router> metrics.counter('c'):inc()
    ---
    ...
    
    test-reload.router> metrics.collect()
    ---
    - - label_pairs:
          alias: router
        timestamp: 1640183661554368
        value: 1
        metric_name: c
    ...
    
    test-reload.router> require("cartridge.roles").reload()
    ---
    - true
    ...
    
    test-reload.router> metrics = require('metrics')
    ---
    ...
    
    test-reload.router> metrics.collect()
    ---
    - []
    ...
    
    test-reload.router> metrics.collectors()
    ---
    - []
    ...
   ```

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Tests
- [x] Changelog

Close #334

### CODE REVIEW

File: test/integration/cartridge_hotreload_test.lua [hunk 1]
```diff
@@ -198,3 +199,34 @@ g.test_cartridge_hotreload_labels_from_config_and_set_labels = function()
...
+    local main_server = g.cluster:server('main')
+    upload_config()
+
+    main_server:exec(function()
+        local metrics = require('cartridge').service_get('metrics')
+        metrics.gauge('hotreload_checker'):set(1)
+    end)
+
+    local resp = main_server:http_request('get', '/new-metrics')
+    t.assert_equals(resp.status, 200)
```
Comment (DifferentialOrange) [inline test/integration/cartridge_hotreload_test.lua:213]: Either set `{raise = false}` in http_request above or remove this check. Also it would be nice if both requests were consistent (both raise errors or bot not raise errors).

**Review by DifferentialOrange — APPROVED** [review]
Seems like it should work. Don't forget to prettify test and squash comments before merge.
