### PR TITLE
Fix broken tests while repeat

### LINKED ISSUE #224: Broken tests with 'repeat'
Some tests (e.g. graphite and cartridge role fails with luatest option `repeat`.
Linked with #195 , #135

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
Tests doesn't work with repeat option. We need to fix:

- [x] graphite test - no call of socket:close() and no waiting until previous graphite workers will be killed
- [x] vinyl test - metrics.clear() call removed registered callbacks 

I didn't forget about

- [x] Tests

Close #224

### CODE REVIEW

File: test/plugins/graphite_test.lua [hunk 1]
```diff
@@ -114,12 +115,13 @@ end
 g.test_graphite_kills_previous_fibers_on_init = function()
```
Comment (vasiliy-t) [inline test/plugins/graphite_test.lua:115]: `graphite.init()` behaves differently when called multiple times:
- it creates multiple graphite workers when called if called without yields between calls
- it creates result in 1 fiber (expected behaviour) when each init call is followed by yield

I think that this will not result in hard to catch bugs but suggest to fix entire init method or at least document the difference.

**Review by vasiliy-t — APPROVED** [review]
