### PR TITLE
fix info.synchro.queue.len

### LINKED ISSUE #399: Error in tnt_synchro_queue_len
tnt_synchro_queue_len table: 0x401e712

### PR DESCRIPTION
**Pull request by panticonur**
Fix `info.synchro.queue.len` type.

- [x] Tests

Close #399

### CODE REVIEW

File: metrics/tarantool/info.lua [hunk 1]
```diff
@@ -57,7 +57,7 @@ local function update_info_metrics()
 
         collectors_list.synchro_queue_len =
             utils.set_gauge('synchro_queue_len', 'Amount of transactions are collecting confirmations now',
-                info.synchro.queue)
+                info.synchro.queue.len)
```
Comment (yngvar-antonsson) [inline metrics/tarantool/info.lua:60]: Please add a simple test to make sure it's working now

**Review by yngvar-antonsson — CHANGES_REQUESTED** [review]

File: metrics/tarantool/info.lua (hunk 1 above)
Comment (panticonur) [reply metrics/tarantool/info.lua:60]: added

**Review by yngvar-antonsson — APPROVED** [review]
