### PR TITLE
Throw an error when http_middelware is processing a wrong handler

### LINKED ISSUE #199: Process latency count more carefully
If user forgets to return correct response object in HTTP handler, it results in "trying to subscribe `nil`" error in this line:
https://github.com/tarantool/metrics/blob/a2d783e5b68475a7c88f89b5ea10ce470d8e67fa/metrics/http_middleware.lua#L75

We should process this more carefully. For example, throw explicit `error("incorrect http handler")`.

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [x] Tests
- [x] Changelog

Close #199

### CODE REVIEW

File: metrics/http_middleware.lua [hunk 1]
```diff
@@ -71,6 +71,9 @@ end
 -- ... arguments for pcall to instrument
 function export.observe(collector, route, ...)
     return collector:observe_latency(function(ok, result)
+        if result == nil then
```
Comment (DifferentialOrange) [inline metrics/http_middleware.lua:74]: non-table result will fail with `trying to subscribe a string value`, so I think `type(result) == 'table'` is the condition.

File: metrics/http_middleware.lua [hunk 2]
```diff
@@ -71,6 +71,9 @@ end
...
+            error("incorrect http handler", 0)
```
Comment (DifferentialOrange) [inline metrics/http_middleware.lua:75]: I think it should be more explicit, like `expecting {status = status, ...}` return

**Review by DifferentialOrange — CHANGES_REQUESTED** [review]

File: metrics/http_middleware.lua (hunk 2 above)
Comment (yngvar-antonsson) [reply metrics/http_middleware.lua:75]: But status can be omitted: 

```lua
status = (not ok and 500) or result.status or 200,
```

**Review by DifferentialOrange — APPROVED** [review]
